import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-mortgage-servicing-escrow-advance-reconciliation",
  "engine": "recovery",
  "title": "Mortgage Servicing Escrow & Corporate Advance Reconciliation",
  "shortTitle": "Mortgage Advance Recovery",
  "tagline": "Reconcile escrow transactions, servicing transfers, force-placed insurance, suspense, and recoverable advances",
  "industry": "Mortgage Servicing Financial Control",
  "uiPort": 4589,
  "apiPort": 5589,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Eligible servicing advances recovered and escrow exceptions remediated with loan-level evidence",
  "valueNarrative": "Connect loan records, investor rules, escrow ledgers, taxes, insurance, servicing advances, suspense, transfers, notices, claims, and reimbursements.",
  "calculation": {
    "actualKey": "recoveredAdvance",
    "expectedKey": "eligibleAdvance",
    "actualLabel": "Recovered Corporate Advances",
    "expectedLabel": "Eligible Recoverable Advances",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Loan, escrow, disbursement, investor, and servicing-advance evidence indicate unrecovered servicing value or account exception.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("loan-and-investor-registry","MAR01","Loan and investor registry","Reconcile loan and investor registry using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed loan and investor registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Loan and investor registry Reference","text","MAR01-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("escrow-transaction-ledger","MAR02","Escrow transaction ledger","Reconcile escrow transaction ledger using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed escrow transaction ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Escrow transaction ledger Reference","text","MAR02-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("tax-disbursement-matching","MAR03","Tax disbursement matching","Reconcile tax disbursement matching using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed tax disbursement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Tax disbursement matching Reference","text","MAR03-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("insurance-disbursement-matching","MAR04","Insurance disbursement matching","Reconcile insurance disbursement matching using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed insurance disbursement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Insurance disbursement matching Reference","text","MAR04-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("escrow-analysis-recalculation","MAR05","Escrow analysis recalculation","Reconcile escrow analysis recalculation using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed escrow analysis recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Escrow analysis recalculation Reference","text","MAR05-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("cushion-limit-validation","MAR06","Cushion-limit validation","Reconcile cushion-limit validation using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed cushion-limit validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Cushion-limit validation Reference","text","MAR06-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("shortage-and-surplus-calculation","MAR07","Shortage and surplus calculation","Reconcile shortage and surplus calculation using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed shortage and surplus calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Shortage and surplus calculation Reference","text","MAR07-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("force-placed-insurance-review","MAR08","Force-placed insurance review","Reconcile force-placed insurance review using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed force-placed insurance review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Force-placed insurance review Reference","text","MAR08-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("corporate-advance-classification","MAR09","Corporate advance classification","Reconcile corporate advance classification using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed corporate advance classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Corporate advance classification Reference","text","MAR09-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("recoverability-and-aging-analysis","MAR10","Recoverability and aging analysis","Reconcile recoverability and aging analysis using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed recoverability and aging analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Recoverability and aging analysis Reference","text","MAR10-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("suspense-account-reconciliation","MAR11","Suspense-account reconciliation","Reconcile suspense-account reconciliation using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed suspense-account reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Suspense-account reconciliation Reference","text","MAR11-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("servicing-transfer-reconciliation","MAR12","Servicing-transfer reconciliation","Reconcile servicing-transfer reconciliation using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed servicing-transfer reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Servicing-transfer reconciliation Reference","text","MAR12-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("investor-claim-preparation","MAR13","Investor claim preparation","Reconcile investor claim preparation using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed investor claim preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Investor claim preparation Reference","text","MAR13-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("borrower-notice-evidence","MAR14","Borrower notice evidence","Reconcile borrower notice evidence using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed borrower notice evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Borrower notice evidence Reference","text","MAR14-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("advance-recovery-ledger","MAR15","Advance recovery ledger","Reconcile advance recovery ledger using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed advance recovery ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Advance recovery ledger Reference","text","MAR15-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]}),
feature("portfolio-and-vendor-analytics","MAR16","Portfolio and vendor analytics","Reconcile portfolio and vendor analytics using loan and investor records, escrow transaction ledgers, tax and insurance disbursements, escrow analyses, force-placed insurance, corporate advances, suspense accounts, transfers, notices, investor claims, and reimbursements.","Produce a governed portfolio and vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["investorLoan","Investor / Loan","text","Northstar Trust / LN-884120"],["caseReference","Portfolio and vendor analytics Reference","text","MAR16-2026-001"],["recoveredAdvance","Recovered Corporate Advances","currency",924000],["eligibleAdvance","Eligible Recoverable Advances","currency",1285000],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredAdvance",subjects:["Servicing transfer portfolio","Defaulted loan cohort","Tax advance population","Insurance advance population","Investor reimbursement claim"]})
]);
